#!/bin/bash

#apache
#/etc/apache2/apache2.conf
#Include sites-enabled/
#Include /home/mist/etc/apache/vhosts


echo "
127.0.2.1    keep tmp webcore myapp
" >> /etc/hosts
chmod 774 /etc/hosts
chgrp mist /etc/hosts

echo "
[xdebug]
xdebug.remote_enable=On
xdebug.remote_host=localhost
xdebug.remote_port=9000
xdebug.remote_handler=dbgp
" >> /etc/php5/apache2/conf.d/xdebug.ini 

# phpunit
pear upgrade PEAR
pear config-set auto_discover 1
pear install pear.phpunit.de/PHPUnit

#pear upgrade PhpDocumentor
