#!/bin/bash

add-apt-repository ppa:chris-lea/node.js
apt-get install nodejs

bash -s stable < <(curl -s https://raw.github.com/wayneeseguin/rvm/master/binscripts/rvm-installer)

rvm install ruby-1.9.3

rvm use 1.9.3 --default

usermod -a -G rvm mist

gem install rubygems-update 
gem udate --system

gem install execjs uglifier sqlite3 sass-rails sass jquery-rails coffee-rails coffee-script coffee-script-source rake therubyracer 

su mist

echo ". /etc/profile.d/rvm.sh" >> ~/.bashrc

exit

